struct structDejaDef {
    int attribut ;
} ;

struct structDejaDef {
    int attribut1 ;
    int attribut2 ;
} ;

int varNonDef(int a) {
    a = b ;
    return 0 ;
}

int varDejaDef(int a) {
    int a ;
    return 0 ;
}

int foncDejaDef() {
    foncNonDef() ;
    return 0 ;
}

int foncDejaDef() {
    return 0 ;
}

int struct_Non_Def() {
    struct structNonDef * s ;
    return 0 ;
}

int returnType() {
    struct structDejaDef * s ;
    return s ;
}

int returnBloc() {
    int a ;
    if (a) {
        return 0 ;
    }
    else {
        int b ;
    }
}

int typeParam(int a, struct structDejaDef * s) {
    return 0 ;
}

int nombreParam() {
    int a ;
    int b ;
    typeParam(a, b) ;
    return 0 ;
}

int cond() {
    int a ;
    nombreParam(a) ;
    if (a = 1) {
        int b ;
    }
    return 0 ;
}

int testType(int a, struct structDejaDef * s) {
    int b ;
    b = a + s ;
    return 0 ;
}

int testFlecheDef(struct structDejaDef * s) {
    s->attribut3 ;
    return 0 ;
}

int divisionParZero(int a) {
    a = a/0 ;
    return 0 ;
}

int testAffectation() {
    3 = 3 ;
    return 0 ;
}

